[package]
name = "resnet-pytorch"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4.3"
# mnist = {version = "0.5.0", features = ["download"]}
ndarray = "0.15.6"
num = "0.4.0"
walkdir = "2.3.2"
wasmedge-nn-common = { path = "../../../wasmedge-nn-common" }